# -*- coding: utf-8 -*-
"""SWING_Portfolio_Notion (6).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wu5_pr35bJBprg0g4oYoGhyKfjxtiI4U
"""



# 이 셀은 중복 생성을 방지하기 위해 비워두었습니다.
# 이제 셀 15를 실행하면 기존 콜아웃의 날짜만 자동으로 업데이트됩니다.

"""# 📈 SWING Portfolio | Notion 자동화 시스템
> Google Colab에서 실행하는 Notion 포트폴리오 자동 동기화 스크립트

---
- **최초 설정 시**: `SETUP_MODE = True` → 페이지/DB 생성 후 ID 자동 저장
- **이후 동기화 시**: `SETUP_MODE = False` → 데이터 자동 업데이트 (블록 삭제 없음)

## 셀 1 · 라이브러리 설치
"""



"""## 셀 2 · 라이브러리 임포트"""

import requests, json, os
from datetime import datetime, date
from collections import defaultdict

try:
    import FinanceDataReader as fdr
    FDR_AVAILABLE = True
    print('✅ FinanceDataReader 로드 완료')
except ImportError:
    FDR_AVAILABLE = False
    print('⚠️ FinanceDataReader 미설치 — 셀 1을 먼저 실행하세요.')

print('✅ 라이브러리 임포트 완료')

"""## 셀 3 · ✏️ 필수 설정값 입력 (직접 수정)
> - `NOTION_TOKEN`: [notion.so/my-integrations](https://www.notion.so/my-integrations) 에서 발급
> - `PARENT_PAGE_ID`: 상위 Notion 페이지 URL 끝 32자리 코드
> - `COLAB_URL`: 이 노트북의 공유 URL (File → Share → Copy link)
"""

# ============================================================
# ✏️ 아래 3가지를 다시 확인하여 입력하세요
# ============================================================

SETUP_MODE     = False   # 설정을 완료했으므로 False로 변경하여 동기화 모드로 전환합니다.

NOTION_TOKEN = os.environ.get('NOTION_TOKEN')
PARENT_PAGE_ID = '382f694e353580cbbc6ae4e7d888f50d'
COLAB_URL      = 'https://colab.research.google.com/drive/1wu5_pr35bJBprg0g4oYoGhyKfjxtiI4U'

# 설정 저장 경로 (자동)
CONFIG_PATH = '/content/swing_config.json'

print(f'SETUP_MODE: {SETUP_MODE}')

"""## 셀 4 · 공통 설정 (수정 불필요)"""

import datetime

HEADERS = {
    'Authorization': f'Bearer {NOTION_TOKEN}',
    'Content-Type': 'application/json',
    'Notion-Version': '2022-06-28'
}
BASE    = 'https://api.notion.com/v1'

# 한국 시간(KST, UTC+9) 설정
tz_kst = datetime.timezone(datetime.timedelta(hours=9))
now_kst = datetime.datetime.now(tz_kst)

TODAY   = now_kst.strftime('%Y-%m-%d')
NOW_STR = now_kst.strftime('%Y-%m-%d %H:%M')

CLASSIFICATION_OPTIONS = [
    {'name': '국내종목',     'color': 'green'},
    {'name': '국내ETF',     'color': 'blue'},
    {'name': '국내ETF-해외','color': 'purple'},
    {'name': '해외종목',     'color': 'orange'},
    {'name': '해외ETF',     'color': 'pink'},
]

print(f'✅ 공통 설정 완료 (한국 시간 적용) | 현재: {NOW_STR}')

"""## 셀 5 · 초기 매매일지 데이터
> 최초 설정 시 Notion DB에 자동 입력되는 초기 거래 데이터입니다.
"""

INITIAL_TRADES = [
    {
        '날짜': '2026-05-19',
        '종목이름': '삼성전자우',
        '티커': '005935',
        '매수매도': '매수',
        '수량': 1,
        '단가': 177900,
        '분류': '국내종목',
        '사유': '국내대장주&주도주의대표종목으로매수결정'
    },
    {
        '날짜': '2026-05-19',
        '종목이름': 'TIGER 200',
        '티커': '102110',
        '매수매도': '매수',
        '수량': 1,
        '단가': 113190,
        '분류': '국내ETF',
        '사유': '국내 대표지수로매수결정'
    },
    {
        '날짜': '2026-05-19',
        '종목이름': 'TIGER 미국S&P500',
        '티커': '360750',
        '매수매도': '매수',
        '수량': 3,
        '단가': 27563,
        '분류': '국내ETF-해외',
        '사유': '미국대표지수로매수결정'
    },
    {
        '날짜': '2026-05-19',
        '종목이름': 'ACE 미국나스닥100',
        '티커': '367380',
        '매수매도': '매수',
        '수량': 5,
        '단가': 33060,
        '분류': '국내ETF-해외',
        '사유': '기술/성장대표지수로매수결정'
    },
    {
        '날짜': '2025-02-22',
        '종목이름': '램리서치',
        '티커': 'LRCX',
        '매수매도': '매수',
        '수량': 1,
        '단가': 127496,
        '분류': '해외종목',
        '사유': '해외 반도체주의 기대 종목으로 매수 결정'
    }
]

print(f'✅ 초기 매매일지 데이터 {len(INITIAL_TRADES)}건 준비 완료')

"""## 셀 6 · DB 스키마 정의 (수정 불필요)"""

TRADE_DB_SCHEMA = {
    '종목이름': {'title': {}},
    '날짜':    {'date': {}},
    '티커':    {'rich_text': {}},
    '매수/매도': {'select': {'options': [
        {'name': '매수', 'color': 'blue'},
        {'name': '매도', 'color': 'red'}
    ]}},
    '수량':   {'number': {'format': 'number'}},
    '단가':   {'number': {'format': 'won'}},
    '분류':   {'select': {'options': CLASSIFICATION_OPTIONS}},
    '사유':   {'rich_text': {}}
}

HOLDINGS_DB_SCHEMA = {
    '종목이름': {'title': {}},
    '티커':    {'rich_text': {}},
    '평가금액': {'number': {'format': 'won'}},
    '수익':    {'number': {'format': 'won'}},
    '수익률':  {'number': {'format': 'percent'}},
    '보유수량': {'number': {'format': 'number'}},
    '매입단가': {'number': {'format': 'won'}},
    '분류':    {'select': {'options': CLASSIFICATION_OPTIONS}}
}

TOTAL_ASSETS_DB_SCHEMA = {
    '작성일자':   {'title': {}},
    '총평가금액': {'number': {'format': 'won'}},
    '총수익':    {'number': {'format': 'won'}},
    '총수익률':  {'number': {'format': 'percent'}}
}

print('✅ DB 스키마 정의 완료')

"""## 셀 7 · Notion API 헬퍼 함수 (수정 불필요)"""

def notion_post(endpoint, payload):
    resp = requests.post(f'{BASE}/{endpoint}', headers=HEADERS, json=payload)
    if resp.status_code not in [200, 201]:
        print(f'❌ API 오류 [{endpoint}]: {resp.status_code} - {resp.text[:300]}')
    return resp.json()

def notion_patch(path, payload):
    resp = requests.patch(f'{BASE}/{path}', headers=HEADERS, json=payload)
    return resp.json()

def notion_get(path, params=None):
    resp = requests.get(f'{BASE}/{path}', headers=HEADERS, params=params)
    return resp.json()

def query_db(db_id, payload=None):
    """DB 전체 조회 (페이지네이션 지원)"""
    results = []
    cursor = None
    while True:
        body = payload.copy() if payload else {}
        if cursor:
            body['start_cursor'] = cursor
        resp = notion_post(f'databases/{db_id}/query', body)
        results.extend(resp.get('results', []))
        if not resp.get('has_more'):
            break
        cursor = resp.get('next_cursor')
    return results

def get_existing_pages(db_id, key_property, key_type='rich_text'):
    """DB에서 key → page_id 매핑 반환"""
    rows = query_db(db_id)
    mapping = {}
    for page in rows:
        props = page['properties']
        try:
            if key_type == 'title':
                key = props[key_property]['title'][0]['text']['content'] if props[key_property]['title'] else ''
            else:
                key = props[key_property]['rich_text'][0]['text']['content'] if props[key_property]['rich_text'] else ''
            if key:
                mapping[key] = page['id']
        except:
            pass
    return mapping

def upsert_page(db_id, existing_map, key, properties):
    """노션 페이지 upsert — 절대 삭제 없이 추가/수정만"""
    if key in existing_map:
        notion_patch(f'pages/{existing_map[key]}', {'properties': properties})
        return 'updated'
    else:
        notion_post('pages', {'parent': {'database_id': db_id}, 'properties': properties})
        return 'inserted'

print('✅ API 헬퍼 함수 정의 완료')

"""## 셀 8 · 메인 페이지 생성 함수 (수정 불필요)"""

def create_database(page_id, title, schema, emoji):
    payload = {
        'parent': {'page_id': page_id},
        'is_inline': True,
        'title': [{'type': 'text', 'text': {'content': f'{emoji} {title}'}}],
        'properties': schema
    }
    db = notion_post('databases', payload)
    db_id = db.get('id', '')
    print(f'  ✅ {emoji} {title} DB 생성: {db_id}')
    return db_id

def create_main_page():
    """SWING Portfolio 메인 페이지 생성 (깔끔한 레이아웃 버전)"""
    payload = {
        'parent': {'page_id': PARENT_PAGE_ID},
        'cover': {
            'type': 'external',
            'external': {
                'url': 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=1500&q=80'
            }
        },
        'icon': {'type': 'emoji', 'emoji': '📈'},
        'properties': {
            'title': {'title': [{'type': 'text', 'text': {'content': 'SWING Portfolio'}}]}}
        ,
        'children': [
            {
                'type': 'callout',
                'callout': {
                    'rich_text': [
                        {'type': 'text', 'text': {'content': f'📅 최근 업데이트:  {NOW_STR}   |   '}, 'annotations': {'color': 'default'}},
                        {'type': 'text', 'text': {'content': '🔄  새로고침 (Google Colab 실행)', 'link': {'url': COLAB_URL}}, 'annotations': {'bold': True, 'color': 'blue'}},
                        {'type': 'text', 'text': {'content': '  ← 클릭 후 Run All 실행'}, 'annotations': {'italic': True, 'color': 'gray'}}
                    ],
                    'icon': {'type': 'emoji', 'emoji': '⚡'},
                    'color': 'gray_background'
                }
            },
            {'type': 'divider', 'divider': {}},
            {'type': 'heading_2', 'heading_2': {'rich_text': [{'type': 'text', 'text': {'content': '💰 총자산'}}]}},
            {'type': 'paragraph', 'paragraph': {'rich_text': []}},
            {'type': 'divider', 'divider': {}},
            {'type': 'heading_2', 'heading_2': {'rich_text': [{'type': 'text', 'text': {'content': '💼 보유주식'}}]}},
            {'type': 'paragraph', 'paragraph': {'rich_text': []}},
            {'type': 'divider', 'divider': {}},
            {'type': 'heading_2', 'heading_2': {'rich_text': [{'type': 'text', 'text': {'content': '📋 매매일지'}}]}},
            {
                'type': 'callout',
                'callout': {
                    'rich_text': [{'type': 'text', 'text': {'content': '가장 최근 날짜의 매매 내역이 위로 오도록 정렬됩니다.'}, 'annotations': {'italic': True, 'color': 'gray'}}],
                    'icon': {'type': 'emoji', 'emoji': 'ℹ️'},
                    'color': 'blue_background'
                }
            },
            {'type': 'paragraph', 'paragraph': {'rich_text': []}}
        ]
    }
    page = notion_post('pages', payload)
    page_id = page.get('id', '')
    if page_id:
        print(f'  ✅ 메인 페이지 생성 완료: {page_id}')
    else:
        print(f'  ❌ 페이지 생성 실패: {page}')
    return page_id

print('✅ 페이지 생성 함수 레이아웃 최적화 완료')

"""## 셀 9 · 매매일지 등록 함수 (수정 불필요)"""

def add_trade(trade_db_id, trade):
    payload = {
        'parent': {'database_id': trade_db_id},
        'properties': {
            '종목이름': {'title': [{'text': {'content': trade['종목이름']}}]},
            '날짜':    {'date':  {'start': trade['날짜']}},
            '티커':    {'rich_text': [{'text': {'content': trade['티커']}}]},
            '매수/매도': {'select': {'name': trade['매수매도']}},
            '수량':    {'number': trade['수량']},
            '단가':    {'number': trade['단가']},
            '분류':    {'select': {'name': trade['분류']}},
            '사유':    {'rich_text': [{'text': {'content': trade['사유']}}]}
        }
    }
    return notion_post('pages', payload)

def load_initial_trades(trade_db_id):
    print(f'  총 {len(INITIAL_TRADES)}건 입력 시작...')
    for trade in INITIAL_TRADES:
        r = add_trade(trade_db_id, trade)
        if 'id' in r:
            print(f"    ✅ {trade['날짜']} | {trade['종목이름']:18s} | {trade['매수매도']} {trade['수량']}주 @ {trade['단가']:,}원")
        else:
            print(f"    ❌ 실패: {trade['종목이름']} → {r.get('message', '')}")

print('✅ 매매일지 등록 함수 정의 완료')

"""## 셀 10 · 현재가 조회 함수 (수정 불필요)"""

import FinanceDataReader as fdr

_price_cache = {}
_usd_krw = None

def get_usd_krw():
    """현재 환율(달러/원) 조회"""
    global _usd_krw
    if _usd_krw: return _usd_krw
    try:
        df = fdr.DataReader('USD/KRW')
        _usd_krw = float(df['Close'].iloc[-1])
        return _usd_krw
    except:
        return 1400.0  # 실패 시 기밴 환율

def get_current_price(ticker, category=''):
    """FinanceDataReader로 현재가 조회 (해외 종목 환율 변환 포함)"""
    if ticker in _price_cache: return _price_cache[ticker]
    if not FDR_AVAILABLE: return None

    try:
        is_us = (category == '해외종목' or ticker.isalpha())
        df = fdr.DataReader(ticker)

        if not df.empty:
            price = float(df['Close'].iloc[-1])
            # 해외 종목(달러 폨기) 경옰 환율 견적 적용
            if is_us:
                rate = get_usd_krw()
                price = price * rate

            _price_cache[ticker] = price
            return price
    except Exception as e:
        print(f'  ⚠️ {ticker} 조회 실패: {e}')
    return None

print('✅ 현재가 조회 함수(환율 변환 추가) 수정 완료')

"""## 셀 11 · 보유주식 계산 함수 (평균단가법)"""

def get_all_trades(trade_db_id):
    """매매일지 전체 조회"""
    rows = query_db(trade_db_id, {'sorts': [{'property': '날짜', 'direction': 'ascending'}]})
    trades = []
    for page in rows:
        props = page['properties']
        try:
            trades.append({
                '날짜':     props['날짜']['date']['start'] if props['날짜']['date'] else '',
                '종목이름': props['종목이름']['title'][0]['text']['content'] if props['종목이름']['title'] else '',
                '티커':     props['티커']['rich_text'][0]['text']['content'] if props['티커']['rich_text'] else '',
                '매수매도': props['매수/매도']['select']['name'] if props['매수/매도']['select'] else '',
                '수량':     props['수량']['number'] or 0,
                '단가':     props['단가']['number'] or 0,
                '분류':     props['분류']['select']['name'] if props['분류']['select'] else '',
            })
        except Exception as e:
            print(f'  ⚠️ 파싱 오류: {e}')
    return trades

def calculate_holdings(trades):
    """매매일지 → 보유주식 계산 (평균단가법)"""
    holdings = {}
    for trade in sorted(trades, key=lambda x: x['날짜']):
        ticker = trade['티커']
        qty    = trade['수량']
        price  = trade['단가']
        action = trade['매수매도']
        if ticker not in holdings:
            holdings[ticker] = {'종목이름': trade['종목이름'], '티커': ticker,
                                '분류': trade['분류'], '보유수량': 0, '총매입금액': 0}
        if action == '매수':
            holdings[ticker]['보유수량']   += qty
            holdings[ticker]['총매입금액'] += qty * price
            holdings[ticker]['종목이름']    = trade['종목이름']
            holdings[ticker]['분류']        = trade['분류']
        elif action == '매도' and holdings[ticker]['보유수량'] > 0:
            remain = holdings[ticker]['보유수량']
            avg    = holdings[ticker]['총매입금액'] / remain
            sold   = min(qty, remain)
            holdings[ticker]['보유수량']   -= sold
            holdings[ticker]['총매입금액'] -= sold * avg
    return {k: v for k, v in holdings.items() if v['보유수량'] > 0}

print('✅ 보유주식 계산 함수 정의 완료')

"""## 셀 12 · DB 업데이트 함수 (수정 불필요)"""

def update_holdings_db(holdings_db_id, holdings, prices):
    """보유주식 DB upsert — 삭제 없음"""
    existing = get_existing_pages(holdings_db_id, '티커', 'rich_text')
    print(f'  기존 {len(existing)}건 → 업데이트 {len(holdings)}건')
    for ticker, data in holdings.items():
        qty        = data['보유수량']
        total_cost = data['총매입금액']
        avg_price  = total_cost / qty if qty > 0 else 0
        cur_price  = prices.get(ticker, avg_price)
        eval_amt   = cur_price * qty
        profit     = eval_amt - total_cost
        profit_rate= profit / total_cost if total_cost > 0 else 0
        props = {
            '종목이름': {'title': [{'text': {'content': data['종목이름']}}]},
            '티커': {'rich_text': [{'text': {'content': ticker}}]},
            '평가금액': {'number': round(eval_amt)},
            '수익': {'number': round(profit)},
            '수익률': {'number': round(profit_rate, 6)},
            '보유수량': {'number': qty},
            '매입단가': {'number': round(avg_price)},
            '분류': {'select': {'name': data['분류']}}
        }
        action = upsert_page(holdings_db_id, existing, ticker, props)
        icon = '🔄' if action == 'updated' else '➕'
        print(f"    {icon} {data['종목이름']:18s} | 평가 {eval_amt:>10,.0f}원 | 수익 {profit:>+10,.0f}원 | {profit_rate*100:+.2f}%")

def update_total_assets_db(total_db_id, holdings, prices):
    """총자산 DB upsert (날짜 기준)"""
    total_eval = total_cost = 0
    for ticker, data in holdings.items():
        qty       = data['보유수량']
        cost      = data['총매입금액']
        cur_price = prices.get(ticker, cost / qty if qty > 0 else 0)
        total_eval += cur_price * qty
        total_cost += cost
    total_profit      = total_eval - total_cost
    total_profit_rate = total_profit / total_cost if total_cost > 0 else 0
    existing = get_existing_pages(total_db_id, '작성일자', 'title')
    props = {
        '작성일자':   {'title': [{'text': {'content': TODAY}}]},
        '총평가금액': {'number': round(total_eval)},
        '총수익': {'number': round(total_profit)},
        '총수익률': {'number': round(total_profit_rate, 6)}
    }
    action = upsert_page(total_db_id, existing, TODAY, props)
    icon = '🔄' if action == 'updated' else '➕'
    print(f'    {icon} {TODAY} | 총평가 {total_eval:,.0f}원 | 총수익 {total_profit:+,.0f}원 | {total_profit_rate*100:+.2f}%')

def update_callout_date(page_id):
    """메인 페이지 최상단 callout 블록을 찾아 한국 시간(NOW_STR)으로 업데이트합니다."""
    clean = page_id.replace('-', '')
    blocks = notion_get(f'blocks/{clean}/children').get('results', [])

    callout_found = False
    for block in blocks:
        if block['type'] == 'callout':
            notion_patch(f"blocks/{block['id']}", {
                'callout': {
                    'rich_text': [
                        {'type': 'text', 'text': {'content': f'📅 최근 업데이트:  {NOW_STR}   |   '}},
                        {'type': 'text', 'text': {'content': '🔄  새로고침 (Google Colab 실행)', 'link': {'url': COLAB_URL}}, 'annotations': {'bold': True, 'color': 'blue'}},
                        {'type': 'text', 'text': {'content': '  ← 클릭 후 Run All 실행'}, 'annotations': {'italic': True, 'color': 'gray'}}
                    ]
                }
            })
            print('    ✅ 노션 콜아웃 업데이트 완료 (한국 시간 적용)')
            callout_found = True
            break

    if not callout_found:
        print('    ⚠️ 콜아웃 블록을 찾지 못했습니다.')

"""## 셀 13 · 전체 동기화 함수 (수정 불필요)"""

def run_sync(main_page_id, trade_db_id, holdings_db_id, total_db_id):
    print(f'\n' + '='*55)
    print(f'🚀 SWING Portfolio 동기화 — {NOW_STR}')
    print('='*55)

    print('\n[Step 1] 매매일지 조회...')
    trades = get_all_trades(trade_db_id)
    print(f'  총 {len(trades)}건 로드')

    print('\n[Step 2] 보유주식 계산...')
    holdings = calculate_holdings(trades)
    print(f'  보유 종목 수: {len(holdings)}')

    print('\n[Step 3] 현재가 조회...')
    prices = {}
    for ticker, data in holdings.items():
        qty = data['보유수량'] if '보유수량' in data else data['보유_수량']
        avg = data['총매입금액'] / qty if qty > 0 else 0
        cur = get_current_price(ticker, data.get('분류', ''))
        prices[ticker] = cur if cur else avg
        src = '시장가' if cur else '매입가(대체)'
        print(f"  {data['종목이름']:18s} ({ticker}): {prices[ticker]:,.2f}원 [{src}]")

    print('\n[Step 4] 보유주식 DB 업데이트...')
    update_holdings_db(holdings_db_id, holdings, prices)

    print('\n[Step 5] 총자산 DB 업데이트...')
    update_total_assets_db(total_db_id, holdings, prices)

    print('\n[Step 6] 메인 페이지 날짜 업데이트...')
    update_callout_date(main_page_id)

    # ================= 수정된 부분 시작 =================
    # 본인의 GitHub 정보를 입력하세요!
    GITHUB_USERNAME = "makeyour2345-cmyk" # 본인 아이디 확인 후 입력
    GITHUB_REPO_NAME = "gaeun"
    
    # 두 개의 값을 받아오도록 수정되었습니다.
    chart_generated, cat_totals = generate_pie_chart(holdings, prices)
    if chart_generated:
        update_chart_in_notion(main_page_id, GITHUB_USERNAME, GITHUB_REPO_NAME, cat_totals)
    # ================= 2줄 추가 =================
    interest_results = analyze_interest_stocks()
    update_interest_in_notion(main_page_id, GITHUB_USERNAME, GITHUB_REPO_NAME, interest_results)
    nps_results = fetch_nps_dart_data()
    update_nps_table_in_notion(main_page_id, nps_results)

"""## 셀 14 · 초기 설정 함수 (수정 불필요)"""

import time

def setup_notion():
    print('\n' + '='*55)
    print('🚀 SWING Portfolio Notion 레이아웃 복구 및 생성')
    print('='*55)

    # 1. 메인 페이지 생성
    p_id = PARENT_PAGE_ID.replace('-', '')
    payload = {
        'parent': {'page_id': p_id},
        'cover': {'type': 'external', 'external': {'url': 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=1500&q=80'}},
        'icon': {'type': 'emoji', 'emoji': '📈'},
        'properties': {'title': {'title': [{'type': 'text', 'text': {'content': 'SWING Portfolio'}}]}}
    }

    page = notion_post('pages', payload)
    page_full_id = page.get('id', '')

    if not page_full_id:
        print(f'  ❌ 메인 페이지 생성 실패: {page}')
        return None

    # URL 경로용 ID 정규화 (모든 하이픈 제거 필수)
    clean_page_id = page_full_id.replace('-', '')
    print(f'  ✅ 메인 페이지 생성 성공: {clean_page_id}')

    def append_blocks_safe(target_id, blocks):
        norm_id = target_id.replace('-', '')
        res = notion_post(f'blocks/{norm_id}/children', {'children': blocks})
        time.sleep(1.5)
        return res

    print('\n[2/4] 레이아웃 구성 중 (구분선 및 섹션 제목)...')

    # 섹션 1: 업데이트 정보 및 구분선
    append_blocks_safe(clean_page_id, [
        {
            'type': 'callout',
            'callout': {
                'rich_text': [
                    {'type': 'text', 'text': {'content': f'📅 최근 업데이트: {NOW_STR}   |   '}},
                    {'type': 'text', 'text': {'content': '🔄 새로고침 (Google Colab 실행)', 'link': {'url': COLAB_URL}}, 'annotations': {'bold': True, 'color': 'blue'}},
                    {'type': 'text', 'text': {'content': '  ← 클릭 후 Run All 실행'}, 'annotations': {'italic': True, 'color': 'gray'}}
                ],
                'icon': {'type': 'emoji', 'emoji': '⚡'}, 'color': 'gray_background'
            }
        },
        {'type': 'divider', 'divider': {}}
    ])

    # 섹션 2: 총자산
    append_blocks_safe(clean_page_id, [{'type': 'heading_2', 'heading_2': {'rich_text': [{'type': 'text', 'text': {'content': '💰 총자산'}}]}}])
    total_db_id = create_database(clean_page_id, '총자산', TOTAL_ASSETS_DB_SCHEMA, '💰').replace('-', '')

    # 섹션 3: 보유주식
    append_blocks_safe(clean_page_id, [
        {'type': 'divider', 'divider': {}},
        {'type': 'heading_2', 'heading_2': {'rich_text': [{'type': 'text', 'text': {'content': '💼 보유주식'}}]}}
    ])
    holdings_db_id = create_database(clean_page_id, '보유주식', HOLDINGS_DB_SCHEMA, '💼').replace('-', '')

    # 섹션 4: 매매일지
    append_blocks_safe(clean_page_id, [
        {'type': 'divider', 'divider': {}},
        {'type': 'heading_2', 'heading_2': {'rich_text': [{'type': 'text', 'text': {'content': '📋 매매일지'}}]}},
        {
            'type': 'callout',
            'callout': {
                'rich_text': [{'type': 'text', 'text': {'content': '가장 최근 날짜의 매매 내역이 위로 오도록 정렬됩니다.'}, 'annotations': {'italic': True, 'color': 'gray'}}],
                'icon': {'type': 'emoji', 'emoji': 'ℹ️'}, 'color': 'blue_background'
            }
        }
    ])
    trade_db_id = create_database(clean_page_id, '매매일지', TRADE_DB_SCHEMA, '📋').replace('-', '')

    print('\n[3/4] 초기 데이터 입력...')
    load_initial_trades(trade_db_id)

    print('\n[4/4] 데이터 동기화...')
    run_sync(clean_page_id, trade_db_id, holdings_db_id, total_db_id)

    config = {
        'MAIN_PAGE_ID': clean_page_id,
        'TRADE_DB_ID': trade_db_id,
        'HOLDINGS_DB_ID': holdings_db_id,
        'TOTAL_ASSETS_DB_ID': total_db_id
    }
    with open(CONFIG_PATH, 'w') as f:
        json.dump(config, f, indent=2, ensure_ascii=False)

    print('\n✅ 모든 레이아웃이 적용된 페이지 생성이 완료되었습니다!')
    return config

import matplotlib.pyplot as plt
import time
from collections import defaultdict

# --- (함수 1) 파이차트 이미지 생성 함수 ---
def generate_pie_chart(holdings, prices, save_path="portfolio_chart.png"):
    import matplotlib.pyplot as plt
    from collections import defaultdict
    print('\n[Step A] 분류별 비율 계산 및 파이차트 생성...')

    # 1. 분류별 평가금액 집계
    category_totals = defaultdict(float)
    for ticker, data in holdings.items():
        qty = data['보유수량']
        cur_price = prices.get(ticker, data['총매입금액'] / qty if qty > 0 else 0)
        eval_amt = cur_price * qty
        category_totals[data['분류']] += eval_amt

    if not category_totals:
        print("  ⚠️ 보유 주식이 없어 차트를 생성하지 않습니다.")
        return False, {}

    # 🌟 [문제 해결 포인트!] 표와 완벽하게 똑같이 '금액이 큰 순서대로' 정렬합니다.
    sorted_totals = sorted(category_totals.items(), key=lambda x: x[1], reverse=True)
    labels = [item[0] for item in sorted_totals]
    sizes = [item[1] for item in sorted_totals]

    # 3. 파이차트 그리기
    plt.figure(figsize=(7, 7))
    try:
        plt.rcParams['font.family'] = 'NanumGothic'
    except:
        pass 
    plt.rcParams['axes.unicode_minus'] = False

    colors = plt.cm.Set3.colors
    plt.pie(sizes, labels=labels, autopct='%1.1f%%', startangle=140, colors=colors,
            wedgeprops={'edgecolor': 'white', 'linewidth': 1.5})
    plt.title('분류별 자산 비중', fontsize=15, pad=20)

    # 4. 이미지 저장
    plt.savefig(save_path, bbox_inches='tight', dpi=150)
    plt.close()

    print(f"  ✅ 파이차트 저장 완료: {save_path}")
    return True, category_totals

# --- (함수 2) 노션에 2단 레이아웃(차트 + 금액 표)으로 강력하게 업데이트하는 함수 ---
def update_chart_in_notion(main_page_id, github_user, github_repo, category_totals):
    import requests
    print('\n[Step B] 노션 페이지 파이차트 및 금액 표 업데이트...')
    clean_page_id = main_page_id.replace('-', '')

    timestamp = int(time.time())
    raw_image_url = f"https://raw.githubusercontent.com/{github_user}/{github_repo}/main/portfolio_chart.png?v={timestamp}"

    # 1. 오른쪽에 들어갈 요약 표(콜아웃) 텍스트 구성
    callout_rich_text = [{"type": "text", "text": {"content": "📊 분류별 평가금액 요약\n\n" }, "annotations": {"bold": True}}]
    for cat, amt in sorted(category_totals.items(), key=lambda x: x[1], reverse=True):
        callout_rich_text.append({"type": "text", "text": {"content": f"• {cat} : "}, "annotations": {"bold": False}})
        callout_rich_text.append({"type": "text", "text": {"content": f"{int(amt):,}원\n"}, "annotations": {"bold": True, "color": "blue"}})

    # 2. 기존 블록 싹 다 찾아서 지우기 (꼬임 방지 초기화)
    blocks = notion_get(f'blocks/{clean_page_id}/children').get('results', [])
    for block in blocks:
        if block['type'] == 'heading_2' and '분류별 비율' in block.get('heading_2', {}).get('rich_text', [{}])[0].get('text', {}).get('content', ''):
            requests.delete(f"{BASE}/blocks/{block['id']}", headers=HEADERS)
        if block['type'] == 'image' and 'portfolio_chart' in block.get('image', {}).get('external', {}).get('url', ''):
            requests.delete(f"{BASE}/blocks/{block['id']}", headers=HEADERS)
        if block['type'] == 'column_list':
            requests.delete(f"{BASE}/blocks/{block['id']}", headers=HEADERS)

    # 3. 새로운 2단 레이아웃 완벽한 규격으로 세팅 (에러 해결 완료!)
    new_blocks = [
        {
            'object': 'block',
            'type': 'divider',
            'divider': {}
        },
        {
            'object': 'block',
            'type': 'heading_2',
            'heading_2': {'rich_text': [{'type': 'text', 'text': {'content': '📊 분류별 비율'}}]}
        },
        {
            'object': 'block',
            'type': 'column_list',
            'column_list': {
                'children': [
                    {
                        'object': 'block',
                        'type': 'column',
                        'column': {
                            'children': [
                                {'object': 'block', 'type': 'image', 'image': {'type': 'external', 'external': {'url': raw_image_url}}}
                            ]
                        }
                    },
                    {
                        'object': 'block',
                        'type': 'column',
                        'column': {
                            'children': [
                                {'object': 'block', 'type': 'callout', 'callout': {'rich_text': callout_rich_text, 'icon': {'type': 'emoji', 'emoji': '💰'}, 'color': 'gray_background'}}
                            ]
                        }
                    }
                ]
            }
        }
    ]
    
    # 4. 노션 API로 강력하게 업데이트 요청
    print("  ⏳ 노션에 새로운 2단 레이아웃 전송 중...")
    resp = requests.patch(f'{BASE}/blocks/{clean_page_id}/children', headers=HEADERS, json={'children': new_blocks})
    
    if resp.status_code == 200:
        print("  ✅ 파이차트 및 금액 표 업데이트 성공!")
    else:
        print(f"  ❌ 에러 발생: {resp.text}")
        raise Exception("노션 업데이트 실패! 로그를 확인하세요.")

# --- (함수 3) 관심종목 지수별 시계열 선 그래프 및 수익률 분석 ---
def analyze_interest_stocks():
    import datetime
    import pandas as pd
    import FinanceDataReader as fdr
    import matplotlib.pyplot as plt
    import matplotlib.dates as mdates
    print('\n[Step C] 관심종목 지수별 시계열 차트 및 수익률 분석...')
    
    stocks = [
        {'name': '테슬라', 'ticker': 'TSLA', 'index': '나스닥100'},
        {'name': '구글(알파벳)', 'ticker': 'GOOG', 'index': '나스닥100'},
        {'name': '엔비디아', 'ticker': 'NVDA', 'index': '나스닥100'},
        {'name': 'SK하이닉스', 'ticker': '000660', 'index': '코스피200'},
        {'name': '현대자동차', 'ticker': '005380', 'index': '코스피200'},
        {'name': '삼성전자', 'ticker': '005930', 'index': '코스피200'},
        {'name': '삼성전자우', 'ticker': '005935', 'index': '코스피200'},
        {'name': '삼성전기', 'ticker': '009150', 'index': '코스피200'},
        {'name': '타이거200', 'ticker': '102110', 'index': '코스피200'},
        {'name': '월마트', 'ticker': 'WMT', 'index': 'S&P500'},
        {'name': '존슨앤드존슨', 'ticker': 'JNJ', 'index': 'S&P500'},
        {'name': '코카콜라', 'ticker': 'KO', 'index': 'S&P500'}
    ]

    index_tickers = {'나스닥100': 'QQQ', '코스피200': '069500', 'S&P500': 'SPY'}
    today = datetime.date.today()
    six_months_ago = today - datetime.timedelta(days=180)

    timeseries_data = {}
    final_returns = {}

    print("  데이터를 수집하고 있습니다. 잠시만 기다려주세요...")
    for idx_name, idx_ticker in index_tickers.items():
        try:
            df = fdr.DataReader(idx_ticker, six_months_ago, today)
            if len(df) > 0:
                df['cum_ret'] = (df['Close'] / df['Close'].iloc[0] - 1) * 100
                timeseries_data[idx_name] = df['cum_ret']
                final_returns[idx_name] = df['cum_ret'].iloc[-1]
        except:
            pass

    for s in stocks:
        try:
            df = fdr.DataReader(s['ticker'], six_months_ago, today)
            if len(df) > 0:
                df['cum_ret'] = (df['Close'] / df['Close'].iloc[0] - 1) * 100
                timeseries_data[s['name']] = df['cum_ret']
                final_returns[s['name']] = df['cum_ret'].iloc[-1]
            else:
                final_returns[s['name']] = 0
        except:
            final_returns[s['name']] = 0

    results = []
    for s in stocks:
        ret = final_returns.get(s['name'], 0)
        idx_ret = final_returns.get(s['index'], 0)
        diff = ret - idx_ret
        status = '🔴 손절 검토' if diff <= -10 else '🟢 유지'
        results.append({
            'name': s['name'], 'index': s['index'], 
            'stock_ret': ret, 'index_ret': idx_ret, 
            'diff': diff, 'status': status
        })

    try:
        plt.rcParams['font.family'] = 'NanumGothic'
    except:
        pass
    plt.rcParams['axes.unicode_minus'] = False

    fig, axes = plt.subplots(3, 1, figsize=(12, 16))
    fig.suptitle('📈 최근 6개월 관심종목 vs 기준지수 추이', fontsize=20, fontweight='bold', y=0.92)

    indices = ['코스피200', '나스닥100', 'S&P500']
    
    for i, idx_name in enumerate(indices):
        ax = axes[i]
        if idx_name in timeseries_data:
            ax.plot(timeseries_data[idx_name].index, timeseries_data[idx_name].values, 
                    label=f'[{idx_name} 지수]', color='black', linewidth=3, linestyle='--')

        group_stocks = [s['name'] for s in stocks if s['index'] == idx_name]
        for s_name in group_stocks:
            if s_name in timeseries_data:
                ax.plot(timeseries_data[s_name].index, timeseries_data[s_name].values, 
                        label=s_name, linewidth=1.5)

        ax.axhline(0, color='gray', linewidth=1, linestyle=':')
        ax.set_title(f'{idx_name} 편입 종목 비교', fontsize=15, pad=10)
        ax.set_ylabel('누적 성장률 (%)', fontsize=12)
        ax.xaxis.set_major_formatter(mdates.DateFormatter('%m월'))
        ax.xaxis.set_major_locator(mdates.MonthLocator())
        ax.legend(loc='center left', bbox_to_anchor=(1.02, 0.5), fontsize=11)
        ax.grid(True, alpha=0.3)

    plt.tight_layout(rect=[0, 0, 0.85, 0.9])
    
    save_path = "interest_chart.png"
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.close()
    
    print(f"  ✅ 3단 선 그래프 차트 저장 완료: {save_path}")
    return results

# --- (함수 4) 노션에 관심종목 차트와 표 강력하게 업데이트 ---
def update_interest_in_notion(main_page_id, github_user, github_repo, results):
    import requests
    import time
    print('\n[Step D] 노션 페이지 관심종목 섹션 업데이트 중...')
    clean_page_id = main_page_id.replace('-', '')
    raw_image_url = f"https://raw.githubusercontent.com/{github_user}/{github_repo}/main/interest_chart.png?v={int(time.time())}"

    blocks = requests.get(f'{BASE}/blocks/{clean_page_id}/children', headers=HEADERS).json().get('results', [])
    delete_ids = []
    is_target_section = False
    
    for block in blocks:
        if block['type'] == 'heading_2' and '관심종목 지수대비 분석' in block.get('heading_2', {}).get('rich_text', [{}])[0].get('text', {}).get('content', ''):
            is_target_section = True
            delete_ids.append(block['id'])
            continue
            
        if is_target_section:
            if block['type'] in ['image', 'table', 'divider']:
                delete_ids.append(block['id'])
            elif block['type'] == 'heading_2':
                is_target_section = False
                
    for b_id in delete_ids:
        requests.delete(f"{BASE}/blocks/{b_id}", headers=HEADERS)

    table_rows = []
    table_rows.append({
        "object": "block",
        "type": "table_row",
        "table_row": {"cells": [
            [{"type": "text", "text": {"content": "종목명"}, "annotations": {"bold": True}}],
            [{"type": "text", "text": {"content": "기준지수"}, "annotations": {"bold": True}}],
            [{"type": "text", "text": {"content": "종목 수익률"}, "annotations": {"bold": True}}],
            [{"type": "text", "text": {"content": "지수 수익률"}, "annotations": {"bold": True}}],
            [{"type": "text", "text": {"content": "수익률 차이"}, "annotations": {"bold": True}}],
            [{"type": "text", "text": {"content": "판정정보"}, "annotations": {"bold": True}}]
        ]}
    })
    
    for r in results:
        color = "red" if r['diff'] <= -10 else "default"
        table_rows.append({
            "object": "block",
            "type": "table_row",
            "table_row": {"cells": [
                [{"type": "text", "text": {"content": str(r['name'])}}],
                [{"type": "text", "text": {"content": str(r['index'])}}],
                [{"type": "text", "text": {"content": f"{r['stock_ret']:.1f}%"}}],
                [{"type": "text", "text": {"content": f"{r['index_ret']:.1f}%"}}],
                [{"type": "text", "text": {"content": f"{r['diff']:.1f}%"}, "annotations": {"color": color}}],
                [{"type": "text", "text": {"content": str(r['status'])}, "annotations": {"bold": True, "color": color}}]
            ]}
        })

    new_blocks = [
        {'object': 'block', 'type': 'divider', 'divider': {}},
        {'object': 'block', 'type': 'heading_2', 'heading_2': {'rich_text': [{'type': 'text', 'text': {'content': '📊 관심종목 지수대비 분석'}}]}},
        {'object': 'block', 'type': 'image', 'image': {'type': 'external', 'external': {'url': raw_image_url}}},
        {'object': 'block', 'type': 'table', 'table': {'table_width': 6, 'has_column_header': True, 'has_row_header': False, 'children': table_rows}}
    ]

    print("  ⏳ 노션에 표와 차트 전송 중...")
    resp = requests.patch(f'{BASE}/blocks/{clean_page_id}/children', headers=HEADERS, json={'children': new_blocks})
    
    if resp.status_code == 200:
        print("  ✅ 노션 표 및 3단 선 그래프 업데이트 성공!")
    else:
        print(f"  ❌ 에러 발생: {resp.text}")
        raise Exception(f"노션 업데이트 실패! 사유: {resp.text}")

# --- (함수 5) 국민연금 최근 2주 공시 긁어오기 (안전 버전) ---
def fetch_nps_dart_data():
    import requests
    import datetime
    import os
    print('\n[Step E] 국민연금공단 DART 공시 조회 중...')
    
    api_key = os.environ.get('DART_API_KEY')
    if not api_key:
        print("  ⚠️ DART API 키가 없습니다. 깃허브 Secrets에 DART_API_KEY를 확인하세요.")
        return []

    # 최근 90일치 데이터 검색
    today = datetime.datetime.today()
    bgn_de = (today - datetime.timedelta(days=90)).strftime('%Y%m%d')
    end_de = today.strftime('%Y%m%d')

    url = "https://opendart.fss.or.kr/api/list.json"
    params = {
        'crtfc_key': api_key,
        'bgn_de': bgn_de,
        'end_de': end_de,
        'pblntf_detail_ty': 'I001', # I001: 주식등의대량보유상황보고서
        'page_count': 100
    }
    
    try:
        res = requests.get(url, params=params)
        data = res.json()
        
        nps_list = []
        if data.get('status') == '000':
            for item in data.get('list', []):
                # 제출인이 '국민연금'이 포함된 것만 뽑기
                if '국민연금' in item.get('flr_nm', ''):
                    nps_list.append({
                        'corp_name': item.get('corp_name'),
                        'date': item.get('rcept_dt')
                    })
        print(f"  ✅ 국민연금 공시 {len(nps_list)}건 찾음!")
        return nps_list
    except Exception as e:
        print(f"  ❌ DART 조회 실패: {e}")
        return []

# --- (함수 6) 노션에 국민연금 표 깔끔하게 업데이트 (중복 삭제 기능 포함) ---
def update_nps_table_in_notion(main_page_id, nps_data):
    import requests
    print('\n[Step F] 노션에 국민연금 표 전송 중...')
    clean_page_id = main_page_id.replace('-', '')
    
    if not nps_data:
        print("  ⚠️ 업데이트할 국민연금 데이터가 없습니다.")
        return

    # 1. 꼬임 방지를 위해 기존에 생성된 국민연금 표 지우기
    blocks = notion_get(f'blocks/{clean_page_id}/children').get('results', [])
    delete_ids = []
    is_target_section = False
    
    for block in blocks:
        if block['type'] == 'heading_2' and '국민연금 매매 동향' in block.get('heading_2', {}).get('rich_text', [{}])[0].get('text', {}).get('content', ''):
            is_target_section = True
            delete_ids.append(block['id'])
            continue
        if is_target_section:
            if block['type'] in ['table', 'divider']:
                delete_ids.append(block['id'])
            elif block['type'] == 'heading_2':
                is_target_section = False
                
    for b_id in delete_ids:
        requests.delete(f"{BASE}/blocks/{b_id}", headers=HEADERS)

    # 2. 표 머리글 만들기
    table_rows = [{
        "object": "block",
        "type": "table_row",
        "table_row": {"cells": [
            [{"type": "text", "text": {"content": "기업명"}, "annotations": {"bold": True}}], 
            [{"type": "text", "text": {"content": "공시 접수일"}, "annotations": {"bold": True}}]
        ]}
    }]
    
    # 3. 데이터 채워넣기 (노션 표가 너무 길어지지 않게 최신 15개까지만)
    for row in nps_data[:15]:
        table_rows.append({
            "object": "block",
            "type": "table_row",
            "table_row": {"cells": [
                [{"type": "text", "text": {"content": row['corp_name']}}],
                [{"type": "text", "text": {"content": row['date']}}]
            ]}
        })
    
    # 4. 맨 아래에 꽂아넣기
    new_blocks = [
        {'object': 'block', 'type': 'divider', 'divider': {}},
        {'object': 'block', 'type': 'heading_2', 'heading_2': {'rich_text': [{'type': 'text', 'text': {'content': '🏢 최근 국민연금 매매 동향 (DART)'}}]}},
        {'object': 'block', 'type': 'table', 'table': {'table_width': 2, 'has_column_header': True, 'has_row_header': False, 'children': table_rows}}
    ]
    
    resp = requests.patch(f'{BASE}/blocks/{clean_page_id}/children', headers=HEADERS, json={'children': new_blocks})
    if resp.status_code == 200:
        print("  ✅ 노션 국민연금 표 업데이트 성공!")
    else:
        print(f"  ❌ 노션 전송 에러: {resp.text}")
        
"""## 셀 15 · 🚀 실행
> - **최초 설정 시** (`SETUP_MODE = True`): 페이지 생성 + DB 생성 + 초기 데이터 입력
> - **이후 동기화 시** (`SETUP_MODE = False`): 현재가 조회 → 보유주식/총자산 업데이트
"""

if 'SETUP_MODE' not in globals():
    SETUP_MODE = False

if SETUP_MODE:
    config = setup_notion()
else:
    if os.path.exists(CONFIG_PATH):
        with open(CONFIG_PATH) as f:
            config = json.load(f)
        print(f'📂 config 로드 완료')
    else:
        # ✏️ 직접 입력이 필요할 경우 여기에 ID를 넣으세요
        config = {
            'MAIN_PAGE_ID':       '382f694e353581c38d1ff7f9965d54e4',
            'TRADE_DB_ID':        '382f694e353581ad80a3fd6d0d043371',
            'HOLDINGS_DB_ID':     '382f694e353581a681bbf2e780a33dfd',
            'TOTAL_ASSETS_DB_ID': '382f694e353581dabf85f8c7791da870'
        }
        print('⚠️ 직접 입력 모드: 설정된 ID로 동기화를 시도합니다.')

    if config:
        run_sync(
            main_page_id   = config['MAIN_PAGE_ID'],
            trade_db_id    = config['TRADE_DB_ID'],
            holdings_db_id = config['HOLDINGS_DB_ID'],
            total_db_id    = config['TOTAL_ASSETS_DB_ID']
        )

# 이 셀은 중복 생성을 방지하기 위해 비워두었습니다.
# 이제 셀 15를 실행하면 기존 콜아웃의 날짜만 자동으로 업데이트됩니다.
